# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\zxt\workspace_py\pyqt\demo2\qt\stackDemo.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(944, 692)
        MainWindow.setMaximumSize(QtCore.QSize(1677721, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setMinimumSize(QtCore.QSize(120, 527))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.horizontalLayout.addWidget(self.listWidget)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.formLayoutWidget = QtWidgets.QWidget(self.page)
        self.formLayoutWidget.setGeometry(QtCore.QRect(90, 80, 381, 371))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.Label = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label.setObjectName("Label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label)
        self.LineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit.setObjectName("LineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit)
        self.Label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.Label_2.setObjectName("Label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_2)
        self.LineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_2)
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        self.pushButton.setGeometry(QtCore.QRect(332, 230, 71, 28))
        self.pushButton.setObjectName("pushButton")
        self.Label_4 = QtWidgets.QLabel(self.page_3)
        self.Label_4.setGeometry(QtCore.QRect(161, 162, 48, 16))
        self.Label_4.setObjectName("Label_4")
        self.LineEdit_3 = QtWidgets.QLineEdit(self.page_3)
        self.LineEdit_3.setGeometry(QtCore.QRect(231, 131, 171, 24))
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.LineEdit_4 = QtWidgets.QLineEdit(self.page_3)
        self.LineEdit_4.setGeometry(QtCore.QRect(231, 162, 171, 24))
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.Label_3 = QtWidgets.QLabel(self.page_3)
        self.Label_3.setGeometry(QtCore.QRect(161, 131, 63, 16))
        self.Label_3.setObjectName("Label_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.page_2)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(40, 30, 160, 80))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setContentsMargins(0, 0, 0, 0)
        self.formLayout_3.setObjectName("formLayout_3")
        self.Label_5 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_5.setObjectName("Label_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Label_5)
        self.LineEdit_5 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_5.setObjectName("LineEdit_5")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.LineEdit_5)
        self.Label_6 = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Label_6.setObjectName("Label_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Label_6)
        self.LineEdit_6 = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        self.LineEdit_6.setObjectName("LineEdit_6")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.LineEdit_6)
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 944, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.listWidget.currentRowChanged['int'].connect(self.stackedWidget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "云空间信息"))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "基础设置"))
        item = self.listWidget.item(2)
        item.setText(_translate("MainWindow", "空间设置"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.Label.setText(_translate("MainWindow", "姓名"))
        self.Label_2.setText(_translate("MainWindow", "地址"))
        self.pushButton.setText(_translate("MainWindow", "保存"))
        self.Label_4.setText(_translate("MainWindow", "secret"))
        self.Label_3.setText(_translate("MainWindow", "appkey："))
        self.Label_5.setText(_translate("MainWindow", "爱好"))
        self.Label_6.setText(_translate("MainWindow", "籍贯"))
